### ISSUE TITLE
Wrong version in SEAPIE prompt

### ISSUE THREAD

**Issue by jolammi** [hirsimaki-markus/SEAPIE#1]
in Seapie.seapie() the version says 1.1, whereas in GitHub page version says 1.2 .

```python
def seapie(self):
    """Main code injector loop"""
    if self.executable is None:
        print("=======[  SEAPIE v1.1 type !help for SEAPIE help  ]=======")
```

**Comment by hirsimaki-markus** [comment]
It seems Pypi package has different version number than the source file on github. This should be fixed if and when later releases happen.
